baseURL : "https://cnawel.github.io/caranchonest/"

title : "Carancho Nest"
theme : PaperMod
defaultContentLanguage : en
defaultContentLanguageInSubdir: false
paginate: 5

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

# menu:
#   main:
#     - identifier: tags
#       name: C0NT3NT
#       url: tags/
#       weight: 10

languages:
    en:
        languageName: "English"
        weight: 1
        languageCode: en-US
        
        disabled: false
        languageDirection: ltr

        menu:
          main:
              - name: Archive
                url: archives
                weight: 5
              - name: Search
                url: search/
                weight: 10
              - name: C0NT3NT
                url: tags
                weight: 10

        homeInfoParams:
          title: "Welcome to **Carancho Nest**"
          content: "> Where the realms of Cybersecurity and Natural Sciences intertwine \n\n
          Embark on a journey through the depths of this nest, where we delve into the captivating worlds of Cybersecurity, Neuroscience, and Nature Science.\n\n\n      
          Whether you're a technology enthusiast, a nature lover, or simply curious about the intricate tapestry that links these domains, **Nido Carancho** is your gateway to unlocking the secrets that lie at the intersection of cutting-edge innovation and the wonders of the natural world
          "

    es:
        weight: 2
        languageName: Spanish
        languageCode: es-AR
        languageAltTitle: Espa帽ol
        
        contentDir: content/es

        disabled: false
        languageDirection: ltr
        menu:
            main:
                - name: Archive
                  url: archives/
                  weight: 5
                - identifier: estags
                  name: C0NT3N1D0
                  url: estags
                  weight: 10
            
        homeInfoParams:
          title: "Bienvenidxs a **Carancho Nest**"
          content: "> D贸nde la Ciberseguridad y las Ciencias Naturales se encuentran \n\n
          Embarcate en un viaje a trav茅s de las profundidades de este Nicho, en d贸nde ahondaremos en los captivos mundos de la Ciberseguridad, la Neurociencia, y las Ciencias Naturales.\n\n\n
          Ya seas un en entusiasta de la tecnolog铆a, un amante de la naturaleza, o por simple curiosidad acerca del intrincado tapiz que une estos dominios, 
          **Carancho Nest** es tu puerta para descubrir los secretos que hay en la intersecci贸n de la innovaci贸n de vanguardia y las maravillas del mundo natural
          "

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

enableEmoji: true

params:
      defaultTheme: auto
      author: c4r4nch0
      env: production # to enable google analytics, opengraph, twitter-cards and schema.

      cover:
            responsiveImages: false
            linkFullImages: false

      socialIcons:
        - name: Github
          url: "https://github.com/cnawel"
        #- name: Youtube
        - name: Rss
          url: "index.xml"

      ShowReadingTime: true
      ShowShareButtons: true
      ShowPostNavLinks: true

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4

# menu:
#   main:
#     - identifier: tags
#       name: C0NT3NT
#       url: "/tags/"
#       weight: 10
    # - identifier: archives
    #   name: Archives
    #   url: /content/
    #   weight: 30

  # module:
  #   mounts: 
  #     - source: content/en
  #       target: content
  #       lang: en
  #     - source: content/es
  #       target: content
  #       lang: es